######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 18 14:56:19 2013
######################################################################

TEMPLATE = app
DEPENDPATH += . src ../harvest/src

# Conda include path - use CONDA_PREFIX environment variable
# Windows uses Library/include subdirectory, Unix uses include directly
win32 {
    CONDA_INCLUDE = $$(CONDA_PREFIX)/Library/include
} else {
    CONDA_INCLUDE = $$(CONDA_PREFIX)/include
}
INCLUDEPATH += . src ../harvest/src
!isEmpty(CONDA_INCLUDE) {
    INCLUDEPATH += $$CONDA_INCLUDE
}

QT += xml
QT += widgets
CONFIG += release c++17
RESOURCES += resource.qrc
ICON = img/gingr.icns

# Build artifacts in separate directories
OBJECTS_DIR = build/obj
MOC_DIR = build/moc
RCC_DIR = build/rcc

# Link against harvest library (built in harvest/ subproject)
LIBS += -L$$OUT_PWD/../lib -lharvest


unix {
	# Ensure C++17 on Unix (Cap'n Proto requires C++14+)
	QMAKE_CXXFLAGS += -std=c++17

	macx {
		TARGET = Gingr
		LIBS += -stdlib=libc++
		QMAKE_CXXFLAGS += -stdlib=libc++
		# AGL framework is deprecated and removed in modern macOS SDKs
		# Override Qt's OpenGL framework settings to only use OpenGL (not AGL)
		QMAKE_LIBS_OPENGL = -framework OpenGL
		# Set to modern macOS to avoid version mismatch warnings
		QMAKE_MACOSX_DEPLOYMENT_TARGET = 11.0
	} else {
		TARGET = gingr
		LIBS += -L. -static-libstdc++ -Wl,--wrap=memcpy
		QMAKE_CXXFLAGS += -include src/memcpyLink.h -D_GNU_SOURCE
		QMAKE_CFLAGS += -include src/memcpyLink.h
	}
}

win32 {
	# Ensure C++17 on Windows (Cap'n Proto requires C++14+)
	QMAKE_CXXFLAGS += /std:c++17
}

# Input
HEADERS += src/Alignment.h \
           src/AlignmentView.h \
           src/AnnotationView.h \
           src/BaseBuffer.h \
           src/BaseImage.h \
           src/BlockStatusBar.h \
           src/BlockView.h \
           src/BlockViewMain.h \
           src/BlockViewMap.h \
           src/DrawingArea.h \
           src/FileInput.h \
           src/FilterControl.h \
		   src/ImportWindow.h \
           src/LcbView.h \
           src/LinkedSplitter.h \
           src/MainWindow.h \
           src/NameListView.h \
           src/OptionButton.h \
           src/OptionPanel.h \
           src/PhylogenyTreeStatusBar.h \
           src/PhylogenyTreeView.h \
           src/PhylogenyTreeViewMain.h \
           src/PhylogenyTreeViewMap.h \
           src/ReferenceView.h \
           src/Region.h \
           src/RegionView.h \
           src/RulerView.h \
           src/SearchControl.h \
           src/SnapshotWindow.h \
           src/SnpBuffer.h \
           src/SnpData.h \
           src/SnpLegend.h \
           src/SnpPalette.h \
           src/SnpWorker.h \
           src/StatusBar.h \
           src/StatusLabel.h \
		   src/SyntenyPalette.h \
           src/Timer.h \
           src/Track.h \
           src/TrackHeightController.h \
           src/TrackListView.h \
           src/TrackView.h \
           src/Tween.h
SOURCES += src/Alignment.cpp \
           src/AlignmentView.cpp \
           src/AnnotationView.cpp \
           src/BaseBuffer.cpp \
           src/BaseImage.cpp \
           src/BlockStatusBar.cpp \
           src/BlockView.cpp \
           src/BlockViewMain.cpp \
           src/BlockViewMap.cpp \
           src/DrawingArea.cpp \
		   src/FileInput.cpp \
           src/FilterControl.cpp \
           src/ImportWindow.cpp \
           src/LcbView.cpp \
           src/LinkedSplitter.cpp \
           src/main.cpp \
           src/MainWindow.cpp \
           src/memcpyWrap.c \
           src/NameListView.cpp \
           src/OptionButton.cpp \
           src/OptionPanel.cpp \
           src/PhylogenyTreeStatusBar.cpp \
           src/PhylogenyTreeView.cpp \
           src/PhylogenyTreeViewMain.cpp \
           src/PhylogenyTreeViewMap.cpp \
           src/ReferenceView.cpp \
           src/Region.cpp \
           src/RegionView.cpp \
           src/RulerView.cpp \
           src/SearchControl.cpp \
           src/SnapshotWindow.cpp \
           src/SnpBuffer.cpp \
           src/SnpData.cpp \
           src/SnpLegend.cpp \
           src/SnpPalette.cpp \
           src/SnpWorker.cpp \
           src/StatusBar.cpp \
           src/StatusLabel.cpp \
		   src/SyntenyPalette.cpp \
           src/Timer.cpp \
           src/Track.cpp \
           src/TrackHeightController.cpp \
           src/TrackListView.cpp \
           src/TrackView.cpp \
           src/Tween.cpp
# Link against conda dependencies
LIBS += -L/Users/david/miniconda3/envs/gingr-build/lib -Wl,-rpath,/Users/david/miniconda3/envs/gingr-build/lib
LIBS += -lprotobuf -labsl_log_internal_check_op -labsl_die_if_null -labsl_log_internal_conditions -labsl_log_internal_message -labsl_examine_stack
LIBS += -labsl_log_internal_format -labsl_log_internal_nullguard -labsl_log_internal_structured_proto -labsl_log_internal_log_sink_set -labsl_log_sink
LIBS += -labsl_log_entry -labsl_log_internal_proto -labsl_flags_internal -labsl_flags_marshalling -labsl_flags_reflection
LIBS += -labsl_flags_private_handle_accessor -labsl_flags_commandlineflag -labsl_flags_commandlineflag_internal -labsl_flags_config -labsl_flags_program_name
LIBS += -labsl_log_initialize -labsl_log_internal_globals -labsl_log_globals -labsl_vlog_config_internal -labsl_log_internal_fnmatch
LIBS += -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_random_distributions -labsl_random_seed_sequences -labsl_random_internal_entropy_pool
LIBS += -labsl_random_internal_randen -labsl_random_internal_randen_hwaes -labsl_random_internal_randen_hwaes_impl -labsl_random_internal_randen_slow
LIBS += -labsl_random_internal_platform -labsl_random_internal_seed_material -labsl_random_seed_gen_exception -labsl_statusor -labsl_status
LIBS += -labsl_cord -labsl_cordz_info -labsl_cord_internal -labsl_cordz_functions -labsl_exponential_biased -labsl_cordz_handle
LIBS += -labsl_crc_cord_state -labsl_crc32c -labsl_crc_internal -labsl_crc_cpu_detect -labsl_leak_check -labsl_strerror
LIBS += -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_kernel_timeout_internal -labsl_stacktrace
LIBS += -labsl_borrowed_fixup_buffer -labsl_hash -labsl_city -labsl_symbolize -labsl_debugging_internal -labsl_demangle_internal
LIBS += -labsl_demangle_rust -labsl_decode_rust_punycode -labsl_utf8_for_code_point -labsl_malloc_internal -labsl_tracing_internal
LIBS += -labsl_time -labsl_civil_time -labsl_time_zone -lutf8_validity -lutf8_range -labsl_strings -labsl_strings_internal
LIBS += -labsl_int128 -labsl_base -labsl_spinlock_wait -labsl_throw_delegate -labsl_raw_logging_internal -labsl_log_severity
LIBS += -lcapnp -lkj -lz
